from scons import devices

# get environment and project
Import('env', 'project')
localenv = env.Clone()

# list of all devices this project supports
devices = devices.list

# appand additional compile flags
localenv.jDev.ccflags   += ' '
localenv.jDev.cxxflags  += ' '
localenv.jDev.linkflags += ' '

if(env.jDev.device in devices):
  #call back to jDev to build the project for us
  env.jDev.BuildProgram(localenv, project)
