# get environment and project
Import('env', 'project', 'device')

env.pm.DependsOn(project, device, 'yalla')

# call back to project manager to build the project for us
env.pm.BuildProject(project, device)
